import * as Fields from "./fields";
export declare function parseStringNotEmpty(value: any, required?: boolean, maxLength?: number, pattern?: Fields.StringConstraintPattern): any;
export declare function StringNotEmpty(required?: boolean, maxLength?: number, pattern?: Fields.StringConstraintPattern): any;
export declare function parseStringNotWhitespace(value: any, required?: boolean, maxLength?: number): any;
export declare function StringNotWhitespace(required?: boolean, maxLength?: number): any;
export declare function parseEmail(value: any, required?: boolean): any;
export declare function Email(required?: boolean): any;
export declare function parseStringPattern(value: any, pattern: Fields.StringConstraintPattern, required?: boolean, minLength?: number, maxLength?: number): any;
export declare function StringPattern(pattern: Fields.StringConstraintPattern, required?: boolean, minLength?: number, maxLength?: number): any;
export declare function parseString(value: any, required?: boolean, minLength?: number, maxLength?: number, pattern?: Fields.StringConstraintPattern): any;
export declare function StringField(required?: boolean, minLength?: number, maxLength?: number, pattern?: Fields.StringConstraintPattern): any;
export declare function StringBase(t: any, required?: boolean, minLength?: number, maxLength?: number, pattern?: Fields.StringConstraintPattern): any;
export declare function parseBoolean(value: any, required?: boolean): any;
export declare function BooleanField(required?: boolean): any;
export declare function BooleanBase(t: any, required?: boolean): any;
export declare function parseDate(value: any, required?: boolean): any;
export declare function DateField(required?: boolean): any;
export declare function DateBase(t: any, required?: boolean): any;
export declare function parseCustomDate(value: any, format: string, required?: boolean, nonStrict?: boolean): any;
export declare function CustomDate(format: string, required?: boolean, nonStrict?: boolean): any;
export declare function CustomDateBase(t: any, format: string, required?: boolean, nonStrict?: boolean): any;
